//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portifolio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portifolio.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am a Full Stack Developer focused on .NET and Blazor, building complete web applications — from user interfaces to API integration and business logic.
        ///
        ///I have experience developing performant and responsive systems, with attention to best practices, clean code, and user experience.
        ///
        ///I aim to build efficient, scalable solutions that solve real problems..
        /// </summary>
        public static string AboutCopy {
            get {
                return ResourceManager.GetString("AboutCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I would love to hear about your project and how I can help. Fill out the form and I will get back to you as soon as possible..
        /// </summary>
        public static string ContactCopy {
            get {
                return ResourceManager.GetString("ContactCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email@example.com.
        /// </summary>
        public static string ContactEmailPlaceholder {
            get {
                return ResourceManager.GetString("ContactEmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string ContactMessage {
            get {
                return ResourceManager.GetString("ContactMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell me about your project.
        /// </summary>
        public static string ContactMessagePlaceholder {
            get {
                return ResourceManager.GetString("ContactMessagePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        public static string ContactNamePlaceholder {
            get {
                return ResourceManager.GetString("ContactNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send message.
        /// </summary>
        public static string ContactSubmit {
            get {
                return ResourceManager.GetString("ContactSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get in touch.
        /// </summary>
        public static string ContactTitle {
            get {
                return ResourceManager.GetString("ContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact me.
        /// </summary>
        public static string HeroCta {
            get {
                return ResourceManager.GetString("HeroCta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, I am Jônatas Gonçalves de Carvalho,.
        /// </summary>
        public static string HeroGreeting {
            get {
                return ResourceManager.GetString("HeroGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Stack Developer.
        /// </summary>
        public static string HeroTitle {
            get {
                return ResourceManager.GetString("HeroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string NavAbout {
            get {
                return ResourceManager.GetString("NavAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string NavContact {
            get {
                return ResourceManager.GetString("NavContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string NavHome {
            get {
                return ResourceManager.GetString("NavHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string NavWork {
            get {
                return ResourceManager.GetString("NavWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML | CSS | JavaScript.
        /// </summary>
        public static string ProjectTech {
            get {
                return ResourceManager.GetString("ProjectTech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Portfolio.
        /// </summary>
        public static string ProjectTitle {
            get {
                return ResourceManager.GetString("ProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front-End.
        /// </summary>
        public static string SkillFrontend {
            get {
                return ResourceManager.GetString("SkillFrontend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# | Html | Css | Explore more.
        /// </summary>
        public static string SkillFrontendCopy {
            get {
                return ResourceManager.GetString("SkillFrontendCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Learning.
        /// </summary>
        public static string SkillMl {
            get {
                return ResourceManager.GetString("SkillMl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/2 year of experience.
        /// </summary>
        public static string SkillMlCopy {
            get {
                return ResourceManager.GetString("SkillMlCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python.
        /// </summary>
        public static string SkillPython {
            get {
                return ResourceManager.GetString("SkillPython", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 years of experience.
        /// </summary>
        public static string SkillPythonCopy {
            get {
                return ResourceManager.GetString("SkillPythonCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string ThemeLabel {
            get {
                return ResourceManager.GetString("ThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects that reflect how I approach problem-solving and build real-world applications..
        /// </summary>
        public static string WorkCopy {
            get {
                return ResourceManager.GetString("WorkCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projects.
        /// </summary>
        public static string WorkTitle {
            get {
                return ResourceManager.GetString("WorkTitle", resourceCulture);
            }
        }
    }
}
