name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore

      - name: Create production appsettings
        run: |
          mkdir -p Portfolio.Web/wwwroot
          cat > Portfolio.Web/wwwroot/appsettings.Production.json << EOF
          {
            "Web3Forms": {
                "AccessKey": "${{ secrets.WEB3FORMS_ACCESS_KEY }}",
                "RecipientEmail": "jonatas.07022003@gmail.com"
            }
          }
          EOF

      - name: Publish
        run: dotnet publish Portfolio.Web/Portfolio.Web.csproj -c Release -o publish

      - name: Add Vercel files
        run: |
          cat > publish/wwwroot/vercel.json << 'EOF'
          {
            "rewrites": [
              {
                "source": "/(.*)",
                "destination": "/index.html"
              }
            ]
          }
          EOF

          mkdir -p publish/wwwroot/.vercel

          cat > publish/wwwroot/.vercel/project.json << EOF
          {
            "orgId": "${{ secrets.VERCEL_ORG_ID }}",
            "projectId": "${{ secrets.VERCEL_PROJECT_ID }}"
          }
          EOF

      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          cd publish/wwwroot
          vercel deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN }}